repos:
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
    -   id: black
        files: \.py$
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.6.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        files: \.[jt]sx?$
        types: [file]