openapi: 3.0.0
info:
  title: API documentation
  version: 1.0.0
  description: API for managing and scheduling ToDo items

paths:
  /suggest:
    get:
      summary: Get suggested free time and ToDo items
      description: Retrieve free time slots and suggested ToDo items
      responses:
        '200':
          description: A list of suggested ToDo items with free time slots
          content:
            application/json:
              schema:
                type: object
                properties:
                  suggest_todos:
                    type: array
                    items:
                      type: object
                      properties:
                        free_time:
                          type: object
                          properties:
                            start:
                              type: string
                              format: date-time
                            end:
                              type: string
                              format: date-time
                            todos:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  title:
                                    type: string
                                  required_time:
                                    type: integer
                                  note:
                                    type: string

  /selected-todo/add:
    patch:
      summary: Add a ToDo item to the selected ToDo list
      description: Add a user's selected ToDo item to the list of ToDos to be done
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                todo_id:
                  type: string
      responses:
        '200':
          description: Empty response indicating successful addition
          content:
            application/json:
              schema:
                type: object

  /selected-todo/remove:
    patch:
      summary: Remove a ToDo item from the selected ToDo list
      description: Remove a user's selected ToDo item from the list of ToDos to be done
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                todo_id:
                  type: string
      responses:
        '200':
          description: Empty response indicating successful removal
          content:
            application/json:
              schema:
                type: object

  /schedule:
    get:
      summary: Get scheduled events and ToDo items
      description: Retrieve calendar events and ToDo items for available time slots
      responses:
        '200':
          description: A list of scheduled events and selected ToDo items
          content:
            application/json:
              schema:
                type: object
                properties:
                  schedule:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: [event, free_time]
                        id:
                          type: string
                        summary:
                          type: string
                          nullable: true
                        description:
                          type: string
                          nullable: true
                        start:
                          type: string
                          format: date-time
                        end:
                          type: string
                          format: date-time
                      required:
                        - type
                        - id
                        - start
                        - end
