import './globals.css';
import { Open_Sans } from 'next/font/google';
import AuthContext from '@/context/AuthContext';
import Footer from '@/components/Footer';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/icons/hukurou.png', sizes: '192x192' },
      { url: '/icons/hukurou.png', sizes: '512x512' },
    ],
    apple: [
      { url: '/icons/hukurou.png' },
      { url: '/icons/hukurou.png', sizes: '512x512' },
    ],
  },
};

export const viewport = 'width=device-width, initial-scale=1';

export const themeColor = '#000000';

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={openSans.className}>
      <body className='w-full max-w-screen-xl overflow-auto mx-auto'>
        <AuthContext>
          <main>{children}</main>
          <Footer />
        </AuthContext>
      </body>
    </html>
  );
}
